### PR TITLE
Added Erase PIN and it's corresponding message

### PR DESCRIPTION
**Pull request by Yury-MonZon**
Added Erase Pin and it's corresponding message.

### CODE REVIEW

**Review by jim17 — CHANGES_REQUESTED** [review]
I don't like the fact that erase pin is fixed to 9999, it's not possibe to be updated. If the user selects pin 9999 in the GUI as pin for its credentials it erases the memtype.

You tested this code ?

EEMEM is not flash, is eeprom. Special function needs to be used to read from eeprom.

Regards,
Miguel.

**Comment by Yury-MonZon** [comment]
It is designed to be set via editing the source code once. And never changed after that. The users with security concerns would remember both PINs and wouldn't use the same code for them both =)

Reading from EEPROM is not done automatically here? My bad, compiler didn't show any error there. You can move it back to FLASH memory, but then you'll have to omit the dummy message - otherwise, it won't fit...

I haven't checked it on the real hardware yet - waiting for my PCB's to be done.

**Comment by jim17** [comment]
ok, the I will wait until you test the code on your own board.

**Comment by Yury-MonZon** [comment]
Updated. Tested on my own hardware. Erase pin is still not configurable through the GUI, only from the firmware source code editing. Which should be enough for most of us.
It does reset the passwords but it doesn't delete the credential names, please see https://github.com/jim17/memtype/issues/21
Thanks!

**Comment by jim17** [comment]
Hello Yury, Ill review your changes during the week and merge it into the main code.

Erase pin function as it name indicates, just set the password back to 0000, but the credentials are encrypted inside the memtype. This is done in this way due to memory constraints of the attiny85 and to have a way to restore your memtype if you missed the pin.

Regards,
Miguel.

**Comment by Yury-MonZon** [comment]
Hi, Jim! Thanks for the reply.
Is there a way to erase all the encrypted data inside it? Would be great to be able to destroy it.

How do I restore the data if the pin is erased? Set it up the correct pin with the MemTypeTool and then it could be accessed again?

**Review by jim17 — APPROVED** [review]

**Comment by jim17** [comment]
@Yury-MonZon merged.

**Pull request merged**
